### ISSUE TITLE
Can't detect element with @CaseInsensitiveXPath(id=true)

### ISSUE THREAD

**Issue by dmtgrinevich** [zebrunner/carina-webdriver#58]
org.openqa.selenium.NoSuchElementException: no such element By.id: .//*[translate(@id, 'PT-ANONCONTRIBS', 'pt-anoncontribs')=translate('pt-anoncontribs', 'PT-ANONCONTRIBS', 'pt-anoncontribs')]
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'MacBook-Pro.local', ip: 'fe80:0:0:0:1464:aff7:23fa:c6ae%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2', java.version: '17.0.6'
Driver info: driver.version: unknown

	at com.zebrunner.carina.webdriver.locator.ExtendedElementLocator.findElement(ExtendedElementLocator.java:267)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
	at jdk.proxy2/jdk.proxy2.$Proxy60.getText(Unknown Source)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement$3.doGetText(ExtendedWebElement.java:1621)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.executeAction(ExtendedWebElement.java:1415)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.overrideAction(ExtendedWebElement.java:1531)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1510)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1487)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.getText(ExtendedWebElement.java:366)
	at com.zebrunner.carina.utils.resources.L10N.verify(L10N.java:191)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1503)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.hover(ExtendedWebElement.java:541)
	at com.zebrunner.carina.webdriver.decorator.ExtendedWebElement.hover(ExtendedWebElement.java:532)
	at com.qaprosoft.carina.demo.gui.pages.desktop.WikipediaLocalePage.hoverContribElem(WikipediaLocalePage.java:94)
	at com.qaprosoft.carina.demo.WebLocalizationSample.testAddNewLanguages(WebLocalizationSample.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Comment by akamarouski** [comment]
invalid issue
